FROM klakegg/hugo:ext-alpine AS hugo-builder

COPY ../ /src
RUN hugo

FROM nginx:alpine

COPY --from=hugo-builder /src/public /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
